name: Publish Binaries

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: edgetx-flasher-nightly.AppImage
            asset_name: edgetx-linux-amd64.AppImage
            binary_ending: AppImage
          - os: windows-latest
            artifact_name: edgetx-flasher-nightly.exe
            asset_name: edgetx-windows-amd64.exe
            binary_ending: exe
          - os: macos-latest
            artifact_name: edgetx-flasher-nightly.dmg
            asset_name: edgetx-macos-amd64.dmg
            binary_ending: dmg

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run electron:build
    - name: Organize Releases
      run: mv dist_electron/*.${{ matrix.binary_ending }} edgetx-flasher-nightly.${{ matrix.binary_ending }}

    - name: Upload binaries to release
      if: github.event_name != 'pull_request'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        overwrite: true
        title: "Latest Build"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        files: edgetx-flasher-nightly.${{ matrix.binary_ending }}
        automatic_release_tag: 'latest'
        prerelease: false
